# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pynifi_client
from pynifi_client.api.policies_api import PoliciesApi  # noqa: E501
from pynifi_client.rest import ApiException


class TestPoliciesApi(unittest.TestCase):
    """PoliciesApi unit test stubs"""

    def setUp(self):
        self.api = pynifi_client.api.policies_api.PoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_access_policy(self):
        """Test case for create_access_policy

        Creates an access policy  # noqa: E501
        """
        pass

    def test_get_access_policy(self):
        """Test case for get_access_policy

        Gets an access policy  # noqa: E501
        """
        pass

    def test_get_access_policy_for_resource(self):
        """Test case for get_access_policy_for_resource

        Gets an access policy for the specified action and resource  # noqa: E501
        """
        pass

    def test_remove_access_policy(self):
        """Test case for remove_access_policy

        Deletes an access policy  # noqa: E501
        """
        pass

    def test_update_access_policy(self):
        """Test case for update_access_policy

        Updates a access policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
