# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.resources_api import ResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.resources_api.ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_resources(self):
        """Test case for get_resources

        Gets the available resources that support access/authorization policies  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
