# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.templates_api import TemplatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.templates_api.TemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_export_template(self):
        """Test case for export_template

        Exports a template  # noqa: E501
        """
        pass

    def test_remove_template(self):
        """Test case for remove_template

        Deletes a template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
