# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.flow_breadcrumb_dto import FlowBreadcrumbDTO  # noqa: F401,E501
from swagger_client.models.permissions_dto import PermissionsDTO  # noqa: F401,E501


class FlowBreadcrumbEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'permissions': 'PermissionsDTO',
        'breadcrumb': 'FlowBreadcrumbDTO'
    }

    attribute_map = {
        'id': 'id',
        'permissions': 'permissions',
        'breadcrumb': 'breadcrumb'
    }

    def __init__(self, id=None, permissions=None, breadcrumb=None):  # noqa: E501
        """FlowBreadcrumbEntity - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._permissions = None
        self._breadcrumb = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if permissions is not None:
            self.permissions = permissions
        if breadcrumb is not None:
            self.breadcrumb = breadcrumb

    @property
    def id(self):
        """Gets the id of this FlowBreadcrumbEntity.  # noqa: E501

        The id of this ancestor ProcessGroup.  # noqa: E501

        :return: The id of this FlowBreadcrumbEntity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FlowBreadcrumbEntity.

        The id of this ancestor ProcessGroup.  # noqa: E501

        :param id: The id of this FlowBreadcrumbEntity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def permissions(self):
        """Gets the permissions of this FlowBreadcrumbEntity.  # noqa: E501

        The permissions for this ancestor ProcessGroup.  # noqa: E501

        :return: The permissions of this FlowBreadcrumbEntity.  # noqa: E501
        :rtype: PermissionsDTO
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this FlowBreadcrumbEntity.

        The permissions for this ancestor ProcessGroup.  # noqa: E501

        :param permissions: The permissions of this FlowBreadcrumbEntity.  # noqa: E501
        :type: PermissionsDTO
        """

        self._permissions = permissions

    @property
    def breadcrumb(self):
        """Gets the breadcrumb of this FlowBreadcrumbEntity.  # noqa: E501

        This breadcrumb.  # noqa: E501

        :return: The breadcrumb of this FlowBreadcrumbEntity.  # noqa: E501
        :rtype: FlowBreadcrumbDTO
        """
        return self._breadcrumb

    @breadcrumb.setter
    def breadcrumb(self, breadcrumb):
        """Sets the breadcrumb of this FlowBreadcrumbEntity.

        This breadcrumb.  # noqa: E501

        :param breadcrumb: The breadcrumb of this FlowBreadcrumbEntity.  # noqa: E501
        :type: FlowBreadcrumbDTO
        """

        self._breadcrumb = breadcrumb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FlowBreadcrumbEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
