# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.remote_process_group_port_dto import RemoteProcessGroupPortDTO  # noqa: F401,E501


class RemoteProcessGroupContentsDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_ports': 'list[RemoteProcessGroupPortDTO]',
        'output_ports': 'list[RemoteProcessGroupPortDTO]'
    }

    attribute_map = {
        'input_ports': 'inputPorts',
        'output_ports': 'outputPorts'
    }

    def __init__(self, input_ports=None, output_ports=None):  # noqa: E501
        """RemoteProcessGroupContentsDTO - a model defined in Swagger"""  # noqa: E501

        self._input_ports = None
        self._output_ports = None
        self.discriminator = None

        if input_ports is not None:
            self.input_ports = input_ports
        if output_ports is not None:
            self.output_ports = output_ports

    @property
    def input_ports(self):
        """Gets the input_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501

        The input ports to which data can be sent.  # noqa: E501

        :return: The input_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501
        :rtype: list[RemoteProcessGroupPortDTO]
        """
        return self._input_ports

    @input_ports.setter
    def input_ports(self, input_ports):
        """Sets the input_ports of this RemoteProcessGroupContentsDTO.

        The input ports to which data can be sent.  # noqa: E501

        :param input_ports: The input_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501
        :type: list[RemoteProcessGroupPortDTO]
        """

        self._input_ports = input_ports

    @property
    def output_ports(self):
        """Gets the output_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501

        The output ports from which data can be retrieved.  # noqa: E501

        :return: The output_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501
        :rtype: list[RemoteProcessGroupPortDTO]
        """
        return self._output_ports

    @output_ports.setter
    def output_ports(self, output_ports):
        """Sets the output_ports of this RemoteProcessGroupContentsDTO.

        The output ports from which data can be retrieved.  # noqa: E501

        :param output_ports: The output_ports of this RemoteProcessGroupContentsDTO.  # noqa: E501
        :type: list[RemoteProcessGroupPortDTO]
        """

        self._output_ports = output_ports

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoteProcessGroupContentsDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
