# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.revision_dto import RevisionDTO  # noqa: F401,E501
from swagger_client.models.variable_registry_dto import VariableRegistryDTO  # noqa: F401,E501


class VariableRegistryEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'process_group_revision': 'RevisionDTO',
        'variable_registry': 'VariableRegistryDTO'
    }

    attribute_map = {
        'process_group_revision': 'processGroupRevision',
        'variable_registry': 'variableRegistry'
    }

    def __init__(self, process_group_revision=None, variable_registry=None):  # noqa: E501
        """VariableRegistryEntity - a model defined in Swagger"""  # noqa: E501

        self._process_group_revision = None
        self._variable_registry = None
        self.discriminator = None

        if process_group_revision is not None:
            self.process_group_revision = process_group_revision
        if variable_registry is not None:
            self.variable_registry = variable_registry

    @property
    def process_group_revision(self):
        """Gets the process_group_revision of this VariableRegistryEntity.  # noqa: E501

        The revision of the Process Group that the Variable Registry belongs to  # noqa: E501

        :return: The process_group_revision of this VariableRegistryEntity.  # noqa: E501
        :rtype: RevisionDTO
        """
        return self._process_group_revision

    @process_group_revision.setter
    def process_group_revision(self, process_group_revision):
        """Sets the process_group_revision of this VariableRegistryEntity.

        The revision of the Process Group that the Variable Registry belongs to  # noqa: E501

        :param process_group_revision: The process_group_revision of this VariableRegistryEntity.  # noqa: E501
        :type: RevisionDTO
        """

        self._process_group_revision = process_group_revision

    @property
    def variable_registry(self):
        """Gets the variable_registry of this VariableRegistryEntity.  # noqa: E501

        The Variable Registry.  # noqa: E501

        :return: The variable_registry of this VariableRegistryEntity.  # noqa: E501
        :rtype: VariableRegistryDTO
        """
        return self._variable_registry

    @variable_registry.setter
    def variable_registry(self, variable_registry):
        """Sets the variable_registry of this VariableRegistryEntity.

        The Variable Registry.  # noqa: E501

        :param variable_registry: The variable_registry of this VariableRegistryEntity.  # noqa: E501
        :type: VariableRegistryDTO
        """

        self._variable_registry = variable_registry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VariableRegistryEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
