# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pynifi_client.models.component_reference_entity import ComponentReferenceEntity  # noqa: F401,E501
from pynifi_client.models.position_dto import PositionDTO  # noqa: F401,E501


class AccessPolicySummaryDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'parent_group_id': 'str',
        'position': 'PositionDTO',
        'resource': 'str',
        'action': 'str',
        'component_reference': 'ComponentReferenceEntity',
        'configurable': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'parent_group_id': 'parentGroupId',
        'position': 'position',
        'resource': 'resource',
        'action': 'action',
        'component_reference': 'componentReference',
        'configurable': 'configurable'
    }

    def __init__(self, id=None, parent_group_id=None, position=None, resource=None, action=None, component_reference=None, configurable=False):  # noqa: E501
        """AccessPolicySummaryDTO - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._parent_group_id = None
        self._position = None
        self._resource = None
        self._action = None
        self._component_reference = None
        self._configurable = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if parent_group_id is not None:
            self.parent_group_id = parent_group_id
        if position is not None:
            self.position = position
        if resource is not None:
            self.resource = resource
        if action is not None:
            self.action = action
        if component_reference is not None:
            self.component_reference = component_reference
        if configurable is not None:
            self.configurable = configurable

    @property
    def id(self):
        """Gets the id of this AccessPolicySummaryDTO.  # noqa: E501

        The id of the component.  # noqa: E501

        :return: The id of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AccessPolicySummaryDTO.

        The id of the component.  # noqa: E501

        :param id: The id of this AccessPolicySummaryDTO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def parent_group_id(self):
        """Gets the parent_group_id of this AccessPolicySummaryDTO.  # noqa: E501

        The id of parent process group of this component if applicable.  # noqa: E501

        :return: The parent_group_id of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: str
        """
        return self._parent_group_id

    @parent_group_id.setter
    def parent_group_id(self, parent_group_id):
        """Sets the parent_group_id of this AccessPolicySummaryDTO.

        The id of parent process group of this component if applicable.  # noqa: E501

        :param parent_group_id: The parent_group_id of this AccessPolicySummaryDTO.  # noqa: E501
        :type: str
        """

        self._parent_group_id = parent_group_id

    @property
    def position(self):
        """Gets the position of this AccessPolicySummaryDTO.  # noqa: E501

        The position of this component in the UI if applicable.  # noqa: E501

        :return: The position of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: PositionDTO
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this AccessPolicySummaryDTO.

        The position of this component in the UI if applicable.  # noqa: E501

        :param position: The position of this AccessPolicySummaryDTO.  # noqa: E501
        :type: PositionDTO
        """

        self._position = position

    @property
    def resource(self):
        """Gets the resource of this AccessPolicySummaryDTO.  # noqa: E501

        The resource for this access policy.  # noqa: E501

        :return: The resource of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this AccessPolicySummaryDTO.

        The resource for this access policy.  # noqa: E501

        :param resource: The resource of this AccessPolicySummaryDTO.  # noqa: E501
        :type: str
        """

        self._resource = resource

    @property
    def action(self):
        """Gets the action of this AccessPolicySummaryDTO.  # noqa: E501

        The action associated with this access policy.  # noqa: E501

        :return: The action of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this AccessPolicySummaryDTO.

        The action associated with this access policy.  # noqa: E501

        :param action: The action of this AccessPolicySummaryDTO.  # noqa: E501
        :type: str
        """
        allowed_values = ["READ", "WRITE"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"  # noqa: E501
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def component_reference(self):
        """Gets the component_reference of this AccessPolicySummaryDTO.  # noqa: E501

        Component this policy references if applicable.  # noqa: E501

        :return: The component_reference of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: ComponentReferenceEntity
        """
        return self._component_reference

    @component_reference.setter
    def component_reference(self, component_reference):
        """Sets the component_reference of this AccessPolicySummaryDTO.

        Component this policy references if applicable.  # noqa: E501

        :param component_reference: The component_reference of this AccessPolicySummaryDTO.  # noqa: E501
        :type: ComponentReferenceEntity
        """

        self._component_reference = component_reference

    @property
    def configurable(self):
        """Gets the configurable of this AccessPolicySummaryDTO.  # noqa: E501

        Whether this policy is configurable.  # noqa: E501

        :return: The configurable of this AccessPolicySummaryDTO.  # noqa: E501
        :rtype: bool
        """
        return self._configurable

    @configurable.setter
    def configurable(self, configurable):
        """Sets the configurable of this AccessPolicySummaryDTO.

        Whether this policy is configurable.  # noqa: E501

        :param configurable: The configurable of this AccessPolicySummaryDTO.  # noqa: E501
        :type: bool
        """

        self._configurable = configurable

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessPolicySummaryDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
