# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pynifi_client.models.connection_status_snapshot_dto import ConnectionStatusSnapshotDTO  # noqa: F401,E501


class ConnectionStatusSnapshotEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'connection_status_snapshot': 'ConnectionStatusSnapshotDTO',
        'can_read': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'connection_status_snapshot': 'connectionStatusSnapshot',
        'can_read': 'canRead'
    }

    def __init__(self, id=None, connection_status_snapshot=None, can_read=False):  # noqa: E501
        """ConnectionStatusSnapshotEntity - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._connection_status_snapshot = None
        self._can_read = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if connection_status_snapshot is not None:
            self.connection_status_snapshot = connection_status_snapshot
        if can_read is not None:
            self.can_read = can_read

    @property
    def id(self):
        """Gets the id of this ConnectionStatusSnapshotEntity.  # noqa: E501

        The id of the connection.  # noqa: E501

        :return: The id of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConnectionStatusSnapshotEntity.

        The id of the connection.  # noqa: E501

        :param id: The id of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def connection_status_snapshot(self):
        """Gets the connection_status_snapshot of this ConnectionStatusSnapshotEntity.  # noqa: E501


        :return: The connection_status_snapshot of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :rtype: ConnectionStatusSnapshotDTO
        """
        return self._connection_status_snapshot

    @connection_status_snapshot.setter
    def connection_status_snapshot(self, connection_status_snapshot):
        """Sets the connection_status_snapshot of this ConnectionStatusSnapshotEntity.


        :param connection_status_snapshot: The connection_status_snapshot of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :type: ConnectionStatusSnapshotDTO
        """

        self._connection_status_snapshot = connection_status_snapshot

    @property
    def can_read(self):
        """Gets the can_read of this ConnectionStatusSnapshotEntity.  # noqa: E501

        Indicates whether the user can read a given resource.  # noqa: E501

        :return: The can_read of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :rtype: bool
        """
        return self._can_read

    @can_read.setter
    def can_read(self, can_read):
        """Sets the can_read of this ConnectionStatusSnapshotEntity.

        Indicates whether the user can read a given resource.  # noqa: E501

        :param can_read: The can_read of this ConnectionStatusSnapshotEntity.  # noqa: E501
        :type: bool
        """

        self._can_read = can_read

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionStatusSnapshotEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
