# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pynifi_client.models.position_dto import PositionDTO  # noqa: F401,E501


class LabelDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'parent_group_id': 'str',
        'position': 'PositionDTO',
        'label': 'str',
        'width': 'float',
        'height': 'float',
        'style': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'id',
        'parent_group_id': 'parentGroupId',
        'position': 'position',
        'label': 'label',
        'width': 'width',
        'height': 'height',
        'style': 'style'
    }

    def __init__(self, id=None, parent_group_id=None, position=None, label=None, width=None, height=None, style=None):  # noqa: E501
        """LabelDTO - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._parent_group_id = None
        self._position = None
        self._label = None
        self._width = None
        self._height = None
        self._style = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if parent_group_id is not None:
            self.parent_group_id = parent_group_id
        if position is not None:
            self.position = position
        if label is not None:
            self.label = label
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height
        if style is not None:
            self.style = style

    @property
    def id(self):
        """Gets the id of this LabelDTO.  # noqa: E501

        The id of the component.  # noqa: E501

        :return: The id of this LabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LabelDTO.

        The id of the component.  # noqa: E501

        :param id: The id of this LabelDTO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def parent_group_id(self):
        """Gets the parent_group_id of this LabelDTO.  # noqa: E501

        The id of parent process group of this component if applicable.  # noqa: E501

        :return: The parent_group_id of this LabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._parent_group_id

    @parent_group_id.setter
    def parent_group_id(self, parent_group_id):
        """Sets the parent_group_id of this LabelDTO.

        The id of parent process group of this component if applicable.  # noqa: E501

        :param parent_group_id: The parent_group_id of this LabelDTO.  # noqa: E501
        :type: str
        """

        self._parent_group_id = parent_group_id

    @property
    def position(self):
        """Gets the position of this LabelDTO.  # noqa: E501

        The position of this component in the UI if applicable.  # noqa: E501

        :return: The position of this LabelDTO.  # noqa: E501
        :rtype: PositionDTO
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this LabelDTO.

        The position of this component in the UI if applicable.  # noqa: E501

        :param position: The position of this LabelDTO.  # noqa: E501
        :type: PositionDTO
        """

        self._position = position

    @property
    def label(self):
        """Gets the label of this LabelDTO.  # noqa: E501

        The text that appears in the label.  # noqa: E501

        :return: The label of this LabelDTO.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this LabelDTO.

        The text that appears in the label.  # noqa: E501

        :param label: The label of this LabelDTO.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def width(self):
        """Gets the width of this LabelDTO.  # noqa: E501

        The width of the label in pixels when at a 1:1 scale.  # noqa: E501

        :return: The width of this LabelDTO.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this LabelDTO.

        The width of the label in pixels when at a 1:1 scale.  # noqa: E501

        :param width: The width of this LabelDTO.  # noqa: E501
        :type: float
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this LabelDTO.  # noqa: E501

        The height of the label in pixels when at a 1:1 scale.  # noqa: E501

        :return: The height of this LabelDTO.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this LabelDTO.

        The height of the label in pixels when at a 1:1 scale.  # noqa: E501

        :param height: The height of this LabelDTO.  # noqa: E501
        :type: float
        """

        self._height = height

    @property
    def style(self):
        """Gets the style of this LabelDTO.  # noqa: E501

        The styles for this label (font-size : 12px, background-color : #eee, etc).  # noqa: E501

        :return: The style of this LabelDTO.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this LabelDTO.

        The styles for this label (font-size : 12px, background-color : #eee, etc).  # noqa: E501

        :param style: The style of this LabelDTO.  # noqa: E501
        :type: dict(str, str)
        """

        self._style = style

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LabelDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
