# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pynifi_client.models.bulletin_entity import BulletinEntity  # noqa: F401,E501
from pynifi_client.models.dimensions_dto import DimensionsDTO  # noqa: F401,E501
from pynifi_client.models.label_dto import LabelDTO  # noqa: F401,E501
from pynifi_client.models.permissions_dto import PermissionsDTO  # noqa: F401,E501
from pynifi_client.models.position_dto import PositionDTO  # noqa: F401,E501
from pynifi_client.models.revision_dto import RevisionDTO  # noqa: F401,E501


class LabelEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'revision': 'RevisionDTO',
        'id': 'str',
        'uri': 'str',
        'position': 'PositionDTO',
        'permissions': 'PermissionsDTO',
        'bulletins': 'list[BulletinEntity]',
        'dimensions': 'DimensionsDTO',
        'component': 'LabelDTO'
    }

    attribute_map = {
        'revision': 'revision',
        'id': 'id',
        'uri': 'uri',
        'position': 'position',
        'permissions': 'permissions',
        'bulletins': 'bulletins',
        'dimensions': 'dimensions',
        'component': 'component'
    }

    def __init__(self, revision=None, id=None, uri=None, position=None, permissions=None, bulletins=None, dimensions=None, component=None):  # noqa: E501
        """LabelEntity - a model defined in Swagger"""  # noqa: E501

        self._revision = None
        self._id = None
        self._uri = None
        self._position = None
        self._permissions = None
        self._bulletins = None
        self._dimensions = None
        self._component = None
        self.discriminator = None

        if revision is not None:
            self.revision = revision
        if id is not None:
            self.id = id
        if uri is not None:
            self.uri = uri
        if position is not None:
            self.position = position
        if permissions is not None:
            self.permissions = permissions
        if bulletins is not None:
            self.bulletins = bulletins
        if dimensions is not None:
            self.dimensions = dimensions
        if component is not None:
            self.component = component

    @property
    def revision(self):
        """Gets the revision of this LabelEntity.  # noqa: E501

        The revision for this request/response. The revision is required for any mutable flow requests and is included in all responses.  # noqa: E501

        :return: The revision of this LabelEntity.  # noqa: E501
        :rtype: RevisionDTO
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this LabelEntity.

        The revision for this request/response. The revision is required for any mutable flow requests and is included in all responses.  # noqa: E501

        :param revision: The revision of this LabelEntity.  # noqa: E501
        :type: RevisionDTO
        """

        self._revision = revision

    @property
    def id(self):
        """Gets the id of this LabelEntity.  # noqa: E501

        The id of the component.  # noqa: E501

        :return: The id of this LabelEntity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LabelEntity.

        The id of the component.  # noqa: E501

        :param id: The id of this LabelEntity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def uri(self):
        """Gets the uri of this LabelEntity.  # noqa: E501

        The URI for futures requests to the component.  # noqa: E501

        :return: The uri of this LabelEntity.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this LabelEntity.

        The URI for futures requests to the component.  # noqa: E501

        :param uri: The uri of this LabelEntity.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def position(self):
        """Gets the position of this LabelEntity.  # noqa: E501

        The position of this component in the UI if applicable.  # noqa: E501

        :return: The position of this LabelEntity.  # noqa: E501
        :rtype: PositionDTO
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this LabelEntity.

        The position of this component in the UI if applicable.  # noqa: E501

        :param position: The position of this LabelEntity.  # noqa: E501
        :type: PositionDTO
        """

        self._position = position

    @property
    def permissions(self):
        """Gets the permissions of this LabelEntity.  # noqa: E501

        The permissions for this component.  # noqa: E501

        :return: The permissions of this LabelEntity.  # noqa: E501
        :rtype: PermissionsDTO
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this LabelEntity.

        The permissions for this component.  # noqa: E501

        :param permissions: The permissions of this LabelEntity.  # noqa: E501
        :type: PermissionsDTO
        """

        self._permissions = permissions

    @property
    def bulletins(self):
        """Gets the bulletins of this LabelEntity.  # noqa: E501

        The bulletins for this component.  # noqa: E501

        :return: The bulletins of this LabelEntity.  # noqa: E501
        :rtype: list[BulletinEntity]
        """
        return self._bulletins

    @bulletins.setter
    def bulletins(self, bulletins):
        """Sets the bulletins of this LabelEntity.

        The bulletins for this component.  # noqa: E501

        :param bulletins: The bulletins of this LabelEntity.  # noqa: E501
        :type: list[BulletinEntity]
        """

        self._bulletins = bulletins

    @property
    def dimensions(self):
        """Gets the dimensions of this LabelEntity.  # noqa: E501


        :return: The dimensions of this LabelEntity.  # noqa: E501
        :rtype: DimensionsDTO
        """
        return self._dimensions

    @dimensions.setter
    def dimensions(self, dimensions):
        """Sets the dimensions of this LabelEntity.


        :param dimensions: The dimensions of this LabelEntity.  # noqa: E501
        :type: DimensionsDTO
        """

        self._dimensions = dimensions

    @property
    def component(self):
        """Gets the component of this LabelEntity.  # noqa: E501


        :return: The component of this LabelEntity.  # noqa: E501
        :rtype: LabelDTO
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this LabelEntity.


        :param component: The component of this LabelEntity.  # noqa: E501
        :type: LabelDTO
        """

        self._component = component

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LabelEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
