# coding: utf-8

"""
    NiFi Rest Api

    The Rest Api provides programmatic access to command and control a NiFi instance in real time. Start and                                              stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.  # noqa: E501

    OpenAPI spec version: 1.4.0
    Contact: dev@nifi.apache.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QueueSizeDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'byte_count': 'int',
        'object_count': 'int'
    }

    attribute_map = {
        'byte_count': 'byteCount',
        'object_count': 'objectCount'
    }

    def __init__(self, byte_count=None, object_count=None):  # noqa: E501
        """QueueSizeDTO - a model defined in Swagger"""  # noqa: E501

        self._byte_count = None
        self._object_count = None
        self.discriminator = None

        if byte_count is not None:
            self.byte_count = byte_count
        if object_count is not None:
            self.object_count = object_count

    @property
    def byte_count(self):
        """Gets the byte_count of this QueueSizeDTO.  # noqa: E501

        The size of objects in a queue.  # noqa: E501

        :return: The byte_count of this QueueSizeDTO.  # noqa: E501
        :rtype: int
        """
        return self._byte_count

    @byte_count.setter
    def byte_count(self, byte_count):
        """Sets the byte_count of this QueueSizeDTO.

        The size of objects in a queue.  # noqa: E501

        :param byte_count: The byte_count of this QueueSizeDTO.  # noqa: E501
        :type: int
        """

        self._byte_count = byte_count

    @property
    def object_count(self):
        """Gets the object_count of this QueueSizeDTO.  # noqa: E501

        The count of objects in a queue.  # noqa: E501

        :return: The object_count of this QueueSizeDTO.  # noqa: E501
        :rtype: int
        """
        return self._object_count

    @object_count.setter
    def object_count(self, object_count):
        """Sets the object_count of this QueueSizeDTO.

        The count of objects in a queue.  # noqa: E501

        :param object_count: The object_count of this QueueSizeDTO.  # noqa: E501
        :type: int
        """

        self._object_count = object_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueueSizeDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
